WITH new_cart AS(
     SELECT CART_ID, GROUP_CONCAT(DISTINCT NAME) AS NAME
     FROM CART_PRODUCTS
     GROUP BY CART_ID
)
SELECT CART_ID
FROM new_cart
WHERE NAME LIKE '%Milk%' AND NAME LIKE '%Yogurt%'
ORDER By 1

