SELECT I.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_TREE T
JOIN ITEM_INFO I ON T.ITEM_ID = I.ITEM_ID
WHERE NOT EXISTS (SELECT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID = I.ITEM_ID)
ORDER BY 1 DESC;