# parent_id에 본인 아이디가 몇번 나왔냐 

WITH parent AS(
SELECT PARENT_ID, COUNT(*) AS cnt
FROM ECOLI_DATA
GROUP BY PARENT_ID
)

SELECT E.ID, IF(P.cnt IS NULL, 0,P.cnt) AS CHILD_COUNT
FROM ECOLI_DATA E 
LEFT JOIN parent P ON E.ID = P.PARENT_ID
ORDER BY 1