SELECT
    A.CAR_ID, 
    A.CAR_TYPE, 
    TRUNCATE(A.DAILY_FEE * 30 * (1 - COALESCE(D.DISCOUNT_RATE, 0) / 100), 0) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR A 
    LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON A.CAR_TYPE = D.CAR_TYPE AND D.DURATION_TYPE = '30일 이상'
WHERE
    A.CAR_TYPE IN ('세단', 'SUV') AND
    TRUNCATE(A.DAILY_FEE * 30 * (1 - COALESCE(D.DISCOUNT_RATE, 0) / 100), 0) >= 500000 AND
    TRUNCATE(A.DAILY_FEE * 30 * (1 - COALESCE(D.DISCOUNT_RATE, 0) / 100), 0) < 2000000 AND
    A.CAR_ID NOT IN (
        SELECT 
            CAR_ID 
        FROM
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE
            (START_DATE BETWEEN '2022-11-01' AND '2022-11-30') OR
            (END_DATE BETWEEN '2022-11-01' AND '2022-11-30') OR
            (START_DATE <= '2022-11-01' AND END_DATE >= '2022-11-30')
    )
ORDER BY 
    FEE DESC, 
    A.CAR_TYPE ASC, 
    A.CAR_ID DESC;