# 서울에 위치한 식당 # 리뷰가 여러개 리뷰의 평균 
SELECT I.REST_ID, 
       MAX(REST_NAME) AS REST_NAME, 
       MAX(FOOD_TYPE) AS FOOD_TYPE,
       MAX(FAVORITES) AS FAVORITES,
       MAX(ADDRESS) AS ADDRESS,
       ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO I 
JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE '서울%'
GROUP BY I.REST_ID
ORDER BY 6 DESC, 4 DESC;