SELECT COUNT(*) AS FISH_COUNT, FISH_NAME
FROM FISH_INFO I
JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
GROUP BY N.FISH_NAME
ORDER BY COUNT(*) DESC;

# FISH_NAME과 FISH_TYPE은 각각 하나밖에 없는 종류와 이름이기떄문에 둘중뭘로 해도 상관없을 듯!