WITH JOINED2021 AS (
    SELECT  *
    FROM    USER_INFO
    WHERE   YEAR(JOINED) = '2021'
)

SELECT      YEAR(B.SALES_DATE) YEAR, MONTH(B.SALES_DATE) MONTH,
            COUNT(DISTINCT B.USER_ID) PURCHASED_USERS,
            ROUND(COUNT(DISTINCT B.USER_ID) / (SELECT COUNT(*) FROM JOINED2021), 1) PURCHASED_RATIO
FROM        JOINED2021 A
INNER JOIN  ONLINE_SALE B ON A.USER_ID = B.USER_ID
GROUP BY    YEAR, MONTH
ORDER BY    YEAR, MONTH