# 같은 맛이지만 다른 공장에서 나온거라 다른 출하번호 
WITH tbl_1 AS(
SELECT J.FLAVOR,SUM(F.TOTAL_ORDER), SUM(J.TOTAL_ORDER), SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) AS sum_count
FROM FIRST_HALF F
JOIN JULY J ON F.FLAVOR = J.FLAVOR
GROUP BY J.FLAVOR
ORDER BY sum_count DESC)

SELECT FLAVOR
FROM tbl_1
LIMIT 3
# SELECT *
# FROM FIRST_HALF F
# JOIN JULY J ON F.FLAVOR = J.FLAVOR
