# 대여 시작일을 기준으로 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 자동차
# SELECT CAR_ID
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
# GROUP BY CAR_ID
# HAVING COUNT(*) >= 5

# 해당 기간 동안의 월별 자동차 ID 별 총 대여 횟수(컬럼명: RECORDS
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31' AND
      CAR_ID IN (SELECT CAR_ID
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
                 GROUP BY CAR_ID
                 HAVING COUNT(*) >= 5)
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY 1, 2 DESC