SELECT SUM(fish_count) AS FISH_COUNT
FROM (SELECT COUNT(*) AS fish_count
FROM FISH_INFO  I 
JOIN FISH_NAME_INFO N ON I.FISH_TYPE= N.FISH_TYPE
GROUP BY FISH_NAME
HAVING FISH_NAME = 'BASS' OR FISH_NAME = 'SNAPPER') AS A 
