# WITH best_emp AS(
# SELECT EMP_NO, SUM(SCORE)
# FROM HR_GRADE 
# WHERE YEAR = 2022
# GROUP BY EMP_NO
# ORDER BY 2 DESC
# LIMIT 1)

SELECT SUM(SCORE) AS SCORE, G.EMP_NO, MAX(EMP_NAME) AS EMP_NAME, 
       MAX(POSITION) AS POSITION, MAX(EMAIL) AS EMAIL
FROM HR_GRADE G
JOIN HR_EMPLOYEES H ON G.EMP_NO = H.EMP_NO
WHERE YEAR = 2022
GROUP BY G.EMP_NO
ORDER BY 1 DESC
LIMIT 1