-- 코드를 입력하세요
WITH A AS(
SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT 
WHERE CATEGORY IN ('과자','국','김치','식용유')
GROUP BY CATEGORY)

SELECT A.CATEGORY, A.MAX_PRICE, F.PRODUCT_NAME
FROM A 
JOIN FOOD_PRODUCT F ON A.MAX_PRICE = F.PRICE AND A.CATEGORY = F.CATEGORY
ORDER BY 2 DESC
                   
# SELECT *
# FROM FOOD_PRODUCT

